### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by jasonlaw** [Concerti-IO/openidconnect_flutter#4]
I can get the reply with my url.
![image](https://user-images.githubusercontent.com/107820/131093390-6abfcf52-c573-4f4f-bc0e-9a7c46fd2b98.png)

But hit error when clicking the Lookup button.
![image](https://user-images.githubusercontent.com/107820/131093565-fba21c36-2c0b-481d-ba62-4640200e879a.png)

Error: Expected a value of type 'List<dynamic>', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:65418/dart_sdk.js:5041:11)
    at Object.castError (http://localhost:65418/dart_sdk.js:5014:15)
    at Object.cast [as as] (http://localhost:65418/dart_sdk.js:5323:17)
    at Function.as_C [as as] (http://localhost:65418/dart_sdk.js:4960:19)
    at Function.fromJson (http://localhost:65418/packages/openidconnect/openidconnect.dart.lib.js:1620:998)
    at getConfiguration (http://localhost:65418/packages/openidconnect/openidconnect.dart.lib.js:376:50)
    at getConfiguration.next (<anonymous>)
    at http://localhost:65418/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:65418/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:65418/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:65418/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:65418/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:65418/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:65418/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:65418/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:65418/dart_sdk.js:37532:13)
    at http://localhost:65418/dart_sdk.js:33303:9

May I know what am I missing? Thanks.

**Comment by zaif-bsol** [comment]
Having same error here. Any solution yet?

**Comment by zaif-bsol** [comment]
You can see in this picture that there is something wrong with assessing values in `json` object

![image](https://user-images.githubusercontent.com/91457685/135822744-7889eedb-6d14-463c-a075-c9d294bea8c9.png)
